// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VibeCity_API.Data;

#nullable disable

namespace VibeCity_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715163843_SyncAllDatabase")]
    partial class SyncAllDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VibeCity_API.Data.AnimalInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnimalType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("animal_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HouseOwnerStudentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("house_owner_student_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("OwnerStudentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_student_id");

                    b.Property<double>("PosX")
                        .HasColumnType("double precision")
                        .HasColumnName("pos_x");

                    b.Property<double>("PosY")
                        .HasColumnType("double precision")
                        .HasColumnName("pos_y");

                    b.Property<double>("PosZ")
                        .HasColumnType("double precision")
                        .HasColumnName("pos_z");

                    b.Property<double>("RotY")
                        .HasColumnType("double precision")
                        .HasColumnName("rot_y");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("animal_instances");
                });

            modelBuilder.Entity("VibeCity_API.Data.BuildingDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsServerChung")
                        .HasColumnType("boolean")
                        .HasColumnName("IsServerChung");

                    b.Property<double>("PosX")
                        .HasColumnType("double precision");

                    b.Property<double>("PosY")
                        .HasColumnType("double precision");

                    b.Property<double>("PosZ")
                        .HasColumnType("double precision");

                    b.Property<double>("RotY")
                        .HasColumnType("double precision");

                    b.Property<string>("StudentId")
                        .HasColumnType("text")
                        .HasColumnName("StudentId");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("VibeCity_API.Data.DawnGateReward", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<string>("NightCycleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("night_cycle_id");

                    b.Property<int>("RewardAmount")
                        .HasColumnType("integer")
                        .HasColumnName("reward_amount");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("student_id");

                    b.HasKey("Id");

                    b.HasIndex("StudentId", "NightCycleId")
                        .IsUnique();

                    b.ToTable("dawn_gate_rewards");
                });

            modelBuilder.Entity("VibeCity_API.Data.HouseChickenIncome", b =>
                {
                    b.Property<string>("HouseOwnerStudentId")
                        .HasColumnType("text")
                        .HasColumnName("house_owner_student_id");

                    b.Property<DateTime?>("LastCollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_collected_at");

                    b.Property<string>("LastCollectorStudentId")
                        .HasColumnType("text")
                        .HasColumnName("last_collector_student_id");

                    b.Property<DateTime>("LastProcessedHour")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_processed_hour");

                    b.Property<int>("PendingCoin")
                        .HasColumnType("integer")
                        .HasColumnName("pending_coin");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("HouseOwnerStudentId");

                    b.ToTable("house_chicken_income");
                });

            modelBuilder.Entity("VibeCity_API.Data.HouseSecurityLock", b =>
                {
                    b.Property<string>("HouseOwnerStudentId")
                        .HasColumnType("text")
                        .HasColumnName("house_owner_student_id");

                    b.Property<string>("AnswerA")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer_a");

                    b.Property<string>("AnswerB")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer_b");

                    b.Property<int>("CorrectAnswer")
                        .HasColumnType("integer")
                        .HasColumnName("correct_answer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("HouseOwnerStudentId");

                    b.ToTable("house_security_locks");
                });

            modelBuilder.Entity("VibeCity_API.Data.LessonDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("QuizJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("VibeCity_API.Data.NpcDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("InteractionRadius")
                        .HasColumnType("double precision");

                    b.Property<string>("NpcType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("npctype");

                    b.Property<double>("SpawnX")
                        .HasColumnType("double precision");

                    b.Property<double>("SpawnY")
                        .HasColumnType("double precision");

                    b.Property<double>("SpawnZ")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Npcs");
                });

            modelBuilder.Entity("VibeCity_API.Data.PlayerInventoryItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_code");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("StudentId", "ItemCode")
                        .IsUnique();

                    b.ToTable("player_inventory");
                });

            modelBuilder.Entity("VibeCity_API.Data.RaidSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttackerStudentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attacker_student_id");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("FailedReturnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_return_at");

                    b.Property<bool>("LockPassed")
                        .HasColumnType("boolean")
                        .HasColumnName("lock_passed");

                    b.Property<bool>("LockRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("lock_required");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TargetStudentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_student_id");

                    b.HasKey("Id");

                    b.ToTable("raid_sessions");
                });

            modelBuilder.Entity("VibeCity_API.Data.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Gpa")
                        .HasColumnType("double precision");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("StudentId");

                    b.Property<int>("SurvivedDays")
                        .HasColumnType("integer")
                        .HasColumnName("survived_days");

                    b.Property<double>("TotalSurvivalMinutes")
                        .HasColumnType("double precision")
                        .HasColumnName("total_survival_minutes");

                    b.Property<string>("UnlockedSkills")
                        .HasColumnType("text")
                        .HasColumnName("unlocked_skills");

                    b.Property<int>("VibeCoin")
                        .HasColumnType("integer")
                        .HasColumnName("vibe_coin");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("VibeCity_API.Data.TeleportTicket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("student_id");

                    b.Property<string>("TargetMap")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_map");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticket_code");

                    b.HasKey("Id");

                    b.HasIndex("TicketCode")
                        .IsUnique();

                    b.ToTable("teleport_tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
