// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VibeCity_API.Data;

#nullable disable

namespace VibeCity_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715132708_UpdateTeleportTicketIdToLowerCase")]
    partial class UpdateTeleportTicketIdToLowerCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VibeCity_API.Data.BuildingDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsServerChung")
                        .HasColumnType("boolean")
                        .HasColumnName("IsServerChung");

                    b.Property<double>("PosX")
                        .HasColumnType("double precision");

                    b.Property<double>("PosY")
                        .HasColumnType("double precision");

                    b.Property<double>("PosZ")
                        .HasColumnType("double precision");

                    b.Property<double>("RotY")
                        .HasColumnType("double precision");

                    b.Property<string>("StudentId")
                        .HasColumnType("text")
                        .HasColumnName("StudentId");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("VibeCity_API.Data.LessonDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("QuizJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("VibeCity_API.Data.NpcDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("InteractionRadius")
                        .HasColumnType("double precision");

                    b.Property<string>("NpcType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("npctype");

                    b.Property<double>("SpawnX")
                        .HasColumnType("double precision");

                    b.Property<double>("SpawnY")
                        .HasColumnType("double precision");

                    b.Property<double>("SpawnZ")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Npcs");
                });

            modelBuilder.Entity("VibeCity_API.Data.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Gpa")
                        .HasColumnType("double precision");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("StudentId");

                    b.Property<int>("SurvivedDays")
                        .HasColumnType("integer")
                        .HasColumnName("survived_days");

                    b.Property<double>("TotalSurvivalMinutes")
                        .HasColumnType("double precision")
                        .HasColumnName("total_survival_minutes");

                    b.Property<string>("UnlockedSkills")
                        .HasColumnType("text")
                        .HasColumnName("unlocked_skills");

                    b.Property<int>("VibeCoin")
                        .HasColumnType("integer")
                        .HasColumnName("vibe_coin");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("VibeCity_API.Data.TeleportTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("student_id");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticket_code");

                    b.HasKey("Id");

                    b.ToTable("teleport_tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
